[build]
  command = "npm install && npm run build"
  publish = ".svelte-kit/netlify"
  functions = "../netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"]