[build]
  base = "/"
  functions = "../netlify/functions"
  publish = ".svelte-kit/netlify"
  command = "npm install && npm run build"
  environment = { NODE_VERSION = "20" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"]