[build]
  base = "/"
  functions = "netlify/functions"
  publish = "frontend/.svelte-kit/netlify"
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  environment = { NODE_VERSION = "20" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"]