[build]
  base = "/"
  functions = "netlify/functions"
  publish = "frontend/dist"
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  environment = { NODE_VERSION = "20" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200